import { Nav } from '@/components/Nav'
import { Footer } from '@/components/Footer'

export const metadata = {
  title: 'Terms of Service — AgencyLead Radar',
  description: 'The terms that govern use of AgencyLead Radar.',
}

export default function TermsPage() {
  return (
    <div className="min-h-screen flex flex-col bg-slate-950">
      <Nav />
      <main className="flex-1 py-16 px-4">
        <div className="max-w-3xl mx-auto">
          <h1 className="text-3xl font-bold text-white mb-2">Terms of Service</h1>
          <p className="text-slate-500 text-sm mb-8">Last updated: [DATE]</p>

          <div className="bg-amber-950/30 border border-amber-800/40 rounded-xl p-4 mb-10">
            <p className="text-amber-200 text-sm">
              <strong>Template notice.</strong> These terms are a starting template provided with the
              software. Before operating this site commercially, replace every [BRACKETED] value and
              have the final text reviewed by qualified legal counsel for your jurisdiction.
            </p>
          </div>

          <div className="space-y-8 text-slate-300 text-sm leading-relaxed">
            <section>
              <h2 className="text-white font-semibold text-lg mb-2">Agreement</h2>
              <p>
                These terms govern your use of AgencyLead Radar (the &ldquo;Service&rdquo;), operated by
                [LEGAL ENTITY NAME]. By using the Service you agree to them. If you do not agree, do
                not use the Service.
              </p>
            </section>

            <section>
              <h2 className="text-white font-semibold text-lg mb-2">Current status of the Service</h2>
              <p>
                The Service is offered on an early-access basis. Paid plans are displayed for
                information only and are not currently active; no payment is collected through this
                site. Features may change or be withdrawn.
              </p>
            </section>

            <section>
              <h2 className="text-white font-semibold text-lg mb-2">Demo access</h2>
              <p>
                Any shared demo account is provided for evaluation only, contains sample data, and is
                read-only. Do not enter confidential or personal information into a demo account.
              </p>
            </section>

            <section>
              <h2 className="text-white font-semibold text-lg mb-2">Acceptable use</h2>
              <ul className="list-disc pl-5 space-y-1.5">
                <li>Do not use the Service unlawfully or to send unlawful or deceptive communications.</li>
                <li>Do not attempt to breach, overload, or disrupt the Service or its infrastructure.</li>
                <li>Do not upload personal data you have no lawful basis to process.</li>
                <li>
                  You are responsible for complying with laws that apply to your outreach, including
                  anti-spam and telemarketing rules such as the CAN-SPAM Act and applicable
                  do-not-call regulations.
                </li>
              </ul>
            </section>

            <section>
              <h2 className="text-white font-semibold text-lg mb-2">Your content</h2>
              <p>
                You retain ownership of the records and notes you enter. You grant us the limited right
                to process that content solely to operate the Service for you. You are responsible for
                the accuracy and lawfulness of what you upload.
              </p>
            </section>

            <section>
              <h2 className="text-white font-semibold text-lg mb-2">AI-generated output</h2>
              <p>
                Audit summaries and outreach drafts are generated by an automated language model from
                the information you supply. Output may be inaccurate or unsuitable. Review and edit
                everything before sending it to a third party. You are solely responsible for any
                message you send.
              </p>
            </section>

            <section>
              <h2 className="text-white font-semibold text-lg mb-2">Disclaimer</h2>
              <p>
                The Service is provided &ldquo;as is&rdquo; and &ldquo;as available&rdquo;, without
                warranties of any kind to the fullest extent permitted by law. We do not warrant that
                the Service will be uninterrupted, error free, or that results will meet your
                expectations.
              </p>
            </section>

            <section>
              <h2 className="text-white font-semibold text-lg mb-2">Limitation of liability</h2>
              <p>
                To the fullest extent permitted by law, [LEGAL ENTITY NAME] will not be liable for
                indirect, incidental, special, consequential, or punitive damages, or for lost profits
                or revenues, arising from your use of the Service.
              </p>
            </section>

            <section>
              <h2 className="text-white font-semibold text-lg mb-2">Termination</h2>
              <p>
                We may suspend or end access to the Service at any time, including for breach of these
                terms.
              </p>
            </section>

            <section>
              <h2 className="text-white font-semibold text-lg mb-2">Governing law</h2>
              <p>These terms are governed by the laws of [JURISDICTION].</p>
            </section>

            <section>
              <h2 className="text-white font-semibold text-lg mb-2">Contact</h2>
              <p>Questions about these terms: [CONTACT EMAIL].</p>
            </section>
          </div>
        </div>
      </main>
      <Footer />
    </div>
  )
}
